### ISSUE TITLE
无需动态申请权限的方式不友好

### ISSUE THREAD

**Issue by FynnJason** [bboylin/UniversalToast#11]
从用户体验来看，当需要弹出可以点击的Toast时，还给用户整个自己开启权限的界面，会影响用户使用。个人建议还是升级为自动申请动态权限，在application中调用init来初始化。

**Comment by bboylin** [comment]
Android 8.0对于悬浮窗权限申请只能那样，如果你有更好的申请方法，请提PR，谢谢~
