### ISSUE TITLE
点击可点击的Toast时，会点到Toast后面的控件。

### ISSUE THREAD

**Issue by FynnJason** [bboylin/UniversalToast#12]
运行Demo出现的，点击Toast后，再在点击查看，但是反应的是Toast后面的事件。请看Gif图
![gif](https://user-images.githubusercontent.com/22359466/35214229-6b38c88c-ff9b-11e7-8b07-cf727efaa6ad.gif)

**Comment by bboylin** [comment]
1.0.5版本修复了。
