### ISSUE TITLE
小米红米手机不能显示Toast

### ISSUE THREAD

**Issue by appdev** [bboylin/UniversalToast#14]
小米红米3 
系统MIUI9 
android 5.11 
不开启悬浮窗不能下是Toast，什么都没有。

同小米 MIX2，MIUI9，Android 8.0。没有开悬浮窗权限，能正常显示

**Comment by bboylin** [comment]
这有点奇怪啊，按理说8.0才需要悬浮窗权限的。你的应用通知权限开了吗？

**Comment by appdev** [comment]
都是默认设置，没有更改，刚测试了一下小米4，MIUI9，Android 版本6.0也不行。
log:
```
E/TAG: 1SystemToast
D/WindowManagerWrapper: WindowManager's addView(view, params) has been hooked.
```

**Comment by appdev** [comment]
在MIX2 8.0系统和红米3 5.1系统上在manifest都声明了
`<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />`权限，权限管理里，两个显示悬浮窗都是关闭的。

**Comment by bboylin** [comment]
从日志来看允许了通知权限，使用的是系统的toast。我猜可能是因为hook了windowmanager导致的，你可以把这个repo clone下来，修改下toast module 里SystemToast类里if (Build.VERSION.SDK_INT < O) {
            setContext(view, new SafeToastContext(context));
        }这句，把<O改成==N，在这俩手机上试下。因为我这里也没红米和mix2,所以只能你试下了。我猜想是因为这个原因，不然的话就是MIUI9的问题。

**Comment by appdev** [comment]
感谢，这样改之后可以了。

**Comment by bboylin** [comment]
我自己的手机是小米6，MIUI9 ， 7.1.1，也测试了API 22 的模拟器，也是hook了windowmanager,没有遇到过问题，我怀疑是MIUI9里Android N以下不能hook windowmanager。除此之外我没有对系统toast做什么。

**Comment by bboylin** [comment]
好的，谢谢你的issue，我马上发新版本1.0.7。
