### ISSUE TITLE
Android 8.1系统NotificationUtils.isNotificationEnabled总是返回true

### ISSUE THREAD

**Issue by congwiny** [bboylin/UniversalToast#15]
- 我把应用通知给关了
![20180328170735937](https://user-images.githubusercontent.com/9621271/38019604-a2b5075c-32aa-11e8-8a1a-7d938df63bd2.jpg)

- 调用NotificationUtils.isNotificationEnabled返回true。下面是我debug跟踪的情况
![20180328170229635](https://user-images.githubusercontent.com/9621271/38019311-d9060974-32a9-11e8-8717-caeb3af98ad2.jpg)

**Comment by congwiny** [comment]
还有就是想问下，Android 8.0设置WindowManager.LayoutParams为啥不能用 TYPE_APPLICATION_PANEL，TYPE_APPLICATION_ATTACHED_DIALOG类型呢？

**Comment by congwiny** [comment]
v4包里提供的一个工具类比较好使
NotificationManagerCompat.from(context).areNotificationsEnabled()

**Comment by bboylin** [comment]
8.0限制了悬浮窗权限，只能用APPLICATION_OVERLAY

**Comment by bboylin** [comment]
试了下还真是，谢谢~

**Comment by congwiny** [comment]
@bboylin android8.0 我试了下TYPE_APPLICATION_PANEL和TYPE_APPLICATION_ATTACHED_DIALOG都可以

**Comment by bboylin** [comment]
嗯对，改过几次忘了测试了。
