### ISSUE TITLE
崩溃BUG

### ISSUE THREAD

**Issue by GoingAI** [bboylin/UniversalToast#16]
![image](https://user-images.githubusercontent.com/9779970/38294771-86076310-381e-11e8-8f86-a9d2eefbf7c2.png)

**Comment by GoingAI** [comment]
从 v1.0.5 更新到 v1.0.8后，报了一堆这个异常。

**Comment by GoingAI** [comment]
建议实现方式参考美团的方案：
https://juejin.im/post/5abdf52851882555731c3dd3

**Comment by bboylin** [comment]
看起来像是你的activity销毁了，所以cancel的地方报错。美团那个我看了，实现大同小异。1.0.5和1.0.8的区别在于，1.0.8在没有通知权限或者可点击时使用自定义window实现伪toast，而1.0.5是只有可点击的使用自定义window实现伪toast，其他情况都是原生toast。

**Comment by GoingAI** [comment]
系统的toast在Activity销毁的时候可以继续显示，美团实现了toast在Activity切换的时候toast无缝的显示。
1.0.8现在的实现方式崩溃几率太高了，进入一个页面获取数据失败弹一个toast，然后关闭当前页面，这种情况直接就崩溃了

**Comment by bboylin** [comment]
美团那个是用snackBar加广播实现的。确实我这里没有这样做。暂时先用原生toast吧。你通知权限被禁掉了吗？这种情况应该会用原生toast的，但是我不知道为啥用的是伪toast。

**Comment by bboylin** [comment]
v1.0.9已修复，可能出现这种bug的地方尽量使用activity context
