### ISSUE TITLE
【Bug】 WindowManager$BadTokenException

### ISSUE THREAD

**Issue by FynnJason** [bboylin/UniversalToast#2]
![bug](https://user-images.githubusercontent.com/22359466/35021278-2abc8f70-fb6b-11e7-9a56-117726d9931f.png)

**Comment by bboylin** [comment]
可点击的toast需要悬浮窗权限 : android.permission.SYSTEM_ALERT_WINDOW

**Comment by bboylin** [comment]
Android 6.0以上请在应用里自行动态申请权限。或者只是运行Demo的话在设置里把权限允许了就ok
