### ISSUE TITLE
是否支持动画

### ISSUE THREAD

**Issue by NicodeLee** [bboylin/UniversalToast#6]
能支持动画体验更好

**Comment by bboylin** [comment]
good issue。因为framework里限制了windowAnimations必须是系统提供的动画，暂时不支持应用定义的动画。

**Comment by bboylin** [comment]
你的意思是icon不是静态的是动画吗？这个可以有。我以为是指toast的出入动画

**Comment by NicodeLee** [comment]
原意是toast的进出动画而已。
不过icon能有动画就更好了。
还有就是Toast的位置应该默认的顶部、中间、底部吧。（用过其他的Toast库顶部会挡住标题栏，不太友好）。

**Comment by bboylin** [comment]
setGravity方法里有yOffset的值可以设置高度。
