### ISSUE TITLE
运行出现依赖冲突

### ISSUE THREAD

**Issue by baohexin** [bboylin/UniversalToast#7]
运行报下面如图错误，百度了说大概是依赖包出现冲突，我as和作者一样的3.0.1.

![20180119140137](https://user-images.githubusercontent.com/21255413/35137084-5edb3208-fd22-11e7-8a61-4e0ae93c3aba.png)

**Comment by bboylin** [comment]
app包名不能为xyz.bboylin.universaltoast，pull下最新代码。
